- name: Harden VPS
  hosts: vps
  become: yes

  vars_files:
    - ../vars/fail2ban.yml
    - ../vars/msmtp.yml

  tasks:
    - name: Ping server to check connection
      ping:

    - name: Install ufw
      ansible.builtin.package:
        name: ufw
        state: present
        update_cache: yes

    - name: Make sure ipv6 is enabled
      ansible.builtin.lineinfile:
        path: /etc/default/ufw
        state: present
        search_string: "IPV6="
        line: "IPV6=yes"
      notify: Reload ufw

    - name: Set default incoming policy to deny
      community.general.ufw:
        policy: deny
        direction: incoming

    - name: Set default outgoing policy to allow
      community.general.ufw:
        policy: allow
        direction: outgoing

    - name: Allow port 22 (SSH)
      community.general.ufw:
        rule: allow
        port: "22"
        proto: tcp

    - name: Allow ports 443 and 80 (HTTPS and HTTP)
      community.general.ufw:
        rule: allow
        port: "{{ item }}"
        proto: tcp
      loop:
        - 443
        - 80

    - name: Enable ufw
      community.general.ufw:
        state: enabled

    - name: Create rohit user with locked password
      ansible.builtin.user:
        name: rohit
        groups: sudo
        shell: /bin/bash
        create_home: yes
        password: "*"

    - name: Add ssh key for the created user
      ansible.posix.authorized_key:
        user: rohit
        state: present
        key: "{{ lookup('file', '~/.ssh/id_netcup_2_worker.pub')  }}"

    - name: Allow passwordless sudo for rohit user
      ansible.builtin.lineinfile:
        path: /etc/sudoers.d/rohit
        line: "rohit ALL=(ALL) NOPASSWD: ALL"
        create: yes
        mode: "0440"
        owner: root
        group: root
        validate: "/usr/sbin/visudo -cf %s"

    - name: Disable password authentication
      ansible.builtin.lineinfile:
        path: /etc/ssh/sshd_config
        line: "PasswordAuthentication no"
        regexp: "^#?PasswordAuthentication"
        state: present
        backup: yes
      notify: Restart sshd

    - name: Disable empty password login
      ansible.builtin.lineinfile:
        path: /etc/ssh/sshd_config
        line: "PermitEmptyPasswords no"
        regexp: "^#?PermitEmptyPassword"
        state: present
        backup: yes
      notify: Restart sshd

    - name: Disable root login
      ansible.builtin.lineinfile:
        path: /etc/ssh/sshd_config
        line: "PermitRootLogin no"
        regexp: "^#?PermitRootLogin"
        state: present
        backup: yes
      notify: Restart sshd

    - name: Harden SSH Server Settings
      block:
        - name: Set strong Ciphers
          ansible.builtin.lineinfile:
            path: /etc/ssh/sshd_config
            regexp: "^#?Ciphers"
            line: "Ciphers chacha20-poly1305@openssh.com,aes256-gcm@openssh.com,aes256-ctr,aes128-ctr"
            state: present
            backup: yes
          notify: Restart sshd

        - name: Set strong MACs
          ansible.builtin.lineinfile:
            path: /etc/ssh/sshd_config
            regexp: "^#?MACs"
            line: "MACs hmac-sha2-512,hmac-sha2-256"
            state: present
            backup: yes
          notify: Restart sshd

        - name: Set strong KexAlgorithms
          ansible.builtin.lineinfile:
            path: /etc/ssh/sshd_config
            regexp: "^#?KexAlgorithms"
            line: "KexAlgorithms curve25519-sha256,curve25519-sha256@libssh.org"
            state: present
            backup: yes
          notify: Restart sshd

        - name: Set ClientAliveInterval
          ansible.builtin.lineinfile:
            path: /etc/ssh/sshd_config
            regexp: "^#?ClientAliveInterval"
            line: "ClientAliveInterval 300"
            state: present
            backup: yes
          notify: Restart sshd

        - name: Set ClientAliveCountMax
          ansible.builtin.lineinfile:
            path: /etc/ssh/sshd_config
            regexp: "^#?ClientAliveCountMax"
            line: "ClientAliveCountMax 0"
            state: present
            backup: yes
          notify: Restart sshd

    - name: Disable IP forwarding (IPv4)
      ansible.posix.sysctl:
        name: net.ipv4.ip_forward
        value: "0"
        state: present
        reload: yes

    - name: Disable IP forwarding (IPv6)
      ansible.posix.sysctl:
        name: net.ipv6.conf.all.forwarding
        value: "0"
        state: present
        reload: yes

    - name: Disable source-routed packets (IPv4)
      ansible.posix.sysctl:
        name: net.ipv4.conf.all.accept_source_route
        value: "0"
        state: present
        reload: yes

    - name: Disable source-routed packets (IPv6)
      ansible.posix.sysctl:
        name: net.ipv6.conf.all.accept_source_route
        value: "0"
        state: present
        reload: yes

    - name: Disable ICMP redirects (IPv4)
      ansible.posix.sysctl:
        name: net.ipv4.conf.all.accept_redirects
        value: "0"
        state: present
        reload: yes

    - name: Disable ICMP redirects (IPv6)
      ansible.posix.sysctl:
        name: net.ipv6.conf.all.accept_redirects
        value: "0"
        state: present
        reload: yes

    - name: Enable Reverse Path Filtering
      ansible.posix.sysctl:
        name: net.ipv4.conf.all.rp_filter
        value: "1"
        state: present
        reload: yes

    - name: Enable Reverse Path Filtering on default interfaces
      ansible.posix.sysctl:
        name: net.ipv4.conf.default.rp_filter
        value: "1"
        state: present
        reload: yes

    - name: Ignore ICMP broadcast requests
      ansible.posix.sysctl:
        name: net.ipv4.icmp_echo_ignore_broadcasts
        value: "1"
        state: present
        reload: yes

    - name: Enable TCP SYN cookies
      ansible.posix.sysctl:
        name: net.ipv4.tcp_syncookies
        value: "1"
        state: present
        reload: yes

    # Optional: Disable IPv6 completely if not needed
    # Comment these out if you plan to use IPv6 later
    - name: Disable IPv6 support
      ansible.posix.sysctl:
        name: net.ipv6.conf.all.disable_ipv6
        value: "1"
        state: present
        reload: yes

    - name: Disable IPv6 support (default)
      ansible.posix.sysctl:
        name: net.ipv6.conf.default.disable_ipv6
        value: "1"
        state: present
        reload: yes

    - name: Install bsd-mailx for mail command support
      ansible.builtin.package:
        name: bsd-mailx
        state: present
        update_cache: yes

    - name: Install msmtp
      ansible.builtin.package:
        name: msmtp
        state: present
        update_cache: yes

    - name: Link msmtp to sendmail for fail2ban email alerts
      ansible.builtin.file:
        src: /usr/bin/msmtp
        dest: /usr/sbin/sendmail
        state: link
        force: true
        owner: root
        group: root
        mode: "0755"

    - name: Configure msmtp
      ansible.builtin.template:
        src: "../templates/msmtprc.j2"
        dest: /etc/msmtprc
        mode: "0644"
        owner: root
        group: root

    - name: Configure fail2ban action.d/msmtp.conf
      ansible.builtin.template:
        src: "../templates/msmtp.conf.j2"
        dest: /etc/fail2ban/action.d/msmtp-whois.conf
        mode: "0644"
        owner: root
        group: root

    - name: Install fail2ban
      ansible.builtin.package:
        name: fail2ban
        state: present
        update_cache: yes

    - name: Configure fail2ban fail2ban.local
      ansible.builtin.template:
        backup: true
        src: "../templates/jail.local.j2"
        dest: /etc/fail2ban/jail.local
        mode: "0644"
        owner: root
        group: root
      notify: Restart fail2ban

    - name: Enable fail2ban service
      ansible.builtin.systemd:
        name: fail2ban
        state: started
        enabled: yes

    - name: Install unattended-upgrades
      ansible.builtin.package:
        name: unattended-upgrades
        state: present
        update_cache: yes

    - name: Enable unattended-upgrades
      ansible.builtin.systemd:
        name: unattended-upgrades
        state: started
        enabled: yes

    - name: Configure unattended-upgrades
      ansible.builtin.template:
        src: "../templates/unattended-updates.j2"
        dest: /etc/apt/apt.conf.d/50unattended-upgrades
        backup: true
        group: root
        owner: root
        mode: "0644"
      notify: Restart unattended-upgrades

  handlers:
    - import_tasks: ../handlers/ufw.yml
    - import_tasks: ../handlers/sshd.yml
    - import_tasks: ../handlers/fail2ban.yml
    - import_tasks: ../handlers/unattended-upgrades.yml
