---
# System Auditing and Logging Configuration
# Sets up comprehensive system activity monitoring and log management
# Uses auditd for system calls and journald for system logs

- name: Install auditd
  # Install the Linux Audit daemon for system call monitoring
  ansible.builtin.package:
    name: auditd
    state: present
    update_cache: yes

- name: Enable auditd service
  # Ensure audit daemon starts on boot
  ansible.builtin.systemd:
    name: auditd
    enabled: true

- name: Configure auditd rules
  # Deploy custom audit rules for tracking system events
  # Rules typically monitor file access, system calls, and user actions
  ansible.builtin.template:
    src: ../../templates/auditd.j2
    dest: /etc/audit/rules.d/audit.rules
    mode: "0640"
    owner: root
    group: root
  notify: Restart auditd

- name: Install auditd CLI tools
  # Install additional audit tools for log analysis and reporting
  # - auditd: Main package containing ausearch and aureport
  # - audispd-plugins: Plugins for real-time event monitoring
  # - auditd-tools: Additional utilities for audit log analysis (Debian package)
  ansible.builtin.package:
    name:
      - auditd
      - audispd-plugins
    state: present
    update_cache: yes

- name: Add log rotation for auditd
  # Configure log rotation to manage audit log size
  # Prevents logs from filling up disk space
  ansible.builtin.template:
    src: ../../templates/auditd-logrotate.j2
    dest: /etc/logrotate.d/auditd
    mode: "0640"
    owner: root
    group: root

- name: Add size limits for auditd
  # Limit individual log file size to 1GB
  # Helps manage disk space while retaining sufficient history
  ansible.builtin.lineinfile:
    search_string: "max_log_file"
    line: "max_log_file = 1024"
    path: /etc/audit/auditd.conf
    state: present
    backup: yes
  notify: Restart auditd

- name: Add no of logs limits to auditd
  # Keep 10 rotated log files
  # Balances history retention with disk usage
  ansible.builtin.lineinfile:
    search_string: "num_logs"
    line: "num_logs = 10"
    path: /etc/audit/auditd.conf
    state: present
    backup: yes

- name: Ensure journald has persistent storage
  # Configure systemd journal to persist logs across reboots
  # Critical for post-incident analysis
  ansible.builtin.lineinfile:
    path: /etc/systemd/journald.conf
    regexp: "^#?Storage="
    line: "Storage=persistent"

- name: Set journald max retention to 500MB
  # Limit journal size to prevent disk space issues
  # 500MB provides good balance of history vs space
  ansible.builtin.lineinfile:
    path: /etc/systemd/journald.conf
    regexp: "^#?SystemMaxUse="
    line: "SystemMaxUse=500M"

- name: Reload journald config
  # Apply new journal configuration
  ansible.builtin.systemd:
    name: systemd-journald
    state: restarted

# Ensure Daily reports, and, log rotation policy for daily reports
- name: Ensure log summary tools are installed
  ansible.builtin.package:
    name: [bsd-mailx, coreutils, grep]
    state: present

- name: Deploy daily security report cron
  ansible.builtin.copy:
    src: ../../files/daily-report.sh
    dest: /etc/cron.daily/daily-security-report
    mode: "0755"
    owner: root
    group: root

- name: Create logrotate config for daily security reports
  ansible.builtin.copy:
    dest: /etc/logrotate.d/daily-security-report
    content: |
      /var/log/daily-security-report-*.log {
          daily
          rotate 7
          missingok
          notifempty
          compress
          delaycompress
          copytruncate
      }
    mode: "0644"
    owner: root
    group: root
